# fly.toml app configuration file generated for gamer-secret-santa on 2023-09-23T23:40:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gamer-secret-santa"
primary_region = "yyz"
console_command = "/rails/bin/rails console"

[build]

[env]
  DATABASE_URL = "sqlite3:///mnt/volume/production.sqlite3"

[[mounts]]
  source = "sqlite3_volume"
  destination = "/mnt/volume"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
